// USERS
const ADD_SESSION = "ADD_SESSION";
const USERS = "USERS";
const CONNECTED_USER = "CONNECTED_USER";
const DISCONNECTED_USER = "DISCONNECTED_USER";

// SOCKET
const CONNECT_SOCKET = "CONNECT_SOCKET";
const SOCKET_EMISSION = "SOCKET_EMISSION";
const USER_LEFT = "USER_LEFT"
const CLEAR_SESSION = "CLEAR_SESSION";
const LEAVE = "LEAVE";

// MATCHES
const MATCHES = "MATCHES";
const NEW_MATCH = "NEW_MATCH"


// CHALLENGES
const GAME_CHALLENGE = "GAME_CHALLENGE"
const GAME_CHALLENGE_ACCEPTED = "GAME_CHALLENGE_ACCEPTED"
const GAME_CHALLENGE_DECLINED = "GAME_CHALLENGE_DECLINED"
const ACCEPT_CHALLENGE = "ACCEPT_CHALLENGE"




export {
    ADD_SESSION,
    USERS,
    CONNECTED_USER,
    DISCONNECTED_USER,
    CONNECT_SOCKET,
    CLEAR_SESSION,
    LEAVE,
    USER_LEFT,
    SOCKET_EMISSION,
    MATCHES,
    NEW_MATCH,
    GAME_CHALLENGE,
    GAME_CHALLENGE_ACCEPTED,
    GAME_CHALLENGE_DECLINED,
    ACCEPT_CHALLENGE
}